  version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/ruby:3.0.0 # ジョブのコマンドが実行されるプライマリ コンテナ
      steps:
        - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
        - run: echo "hello world" # `echo` コマンドを実行します
